AWSTemplateFormatVersion: '2010-09-09'
Description: Low-cost ECS Fargate with public IP (DEV only)

Parameters:

  Module:
    Type: String
    Default: facturero-sri

  EnvironmentId:
    Type: String
    Default: dev
    AllowedValues: [dev, qa, prd]

  VpcID:
    Type: String

  PublicSubnetIDs:
    Type: CommaDelimitedList

  SSLCertificateArn:
    Type: String

  ContainerPort:
    Type: Number
    Default: 8080

  Cpu:
    Type: String
    Default: 256
    AllowedValues: [256, 512, 1024]

  Memory:
    Type: String
    Default: 512
    AllowedValues: [512, 1024]

  ImageTag:
    Type: String
    Default: 1.0.0

Resources:

# ======================
# SECURITY GROUPS
# ======================

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB SG
      VpcId: !Ref VpcID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS SG
      VpcId: !Ref VpcID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: !Ref ALBSecurityGroup

# ======================
# LOAD BALANCER
# ======================

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${EnvironmentId}-${Module}-alb"
      Scheme: internet-facing
      Type: application
      Subnets: !Ref PublicSubnetIDs
      SecurityGroups:
        - !Ref ALBSecurityGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${EnvironmentId}-${Module}-tg"
      TargetType: ip
      Protocol: HTTP
      Port: !Ref ContainerPort
      VpcId: !Ref VpcID
      HealthCheckPath: /api/health
      Matcher:
        HttpCode: 200-399

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref SSLCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

# ======================
# LOGGING
# ======================

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/ecs/${EnvironmentId}-${Module}"
      RetentionInDays: 7

# ======================
# TASK DEFINITION
# ======================

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${EnvironmentId}-${Module}"
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${EnvironmentId}-${Module}-ECSRole
      TaskRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${EnvironmentId}-${Module}-ECSRole
      ContainerDefinitions:
        - Name: api
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EnvironmentId}-facturero-sri:${ImageTag}"
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Environment:
            - Name: PORT
              Value: !Ref ContainerPort
            - Name: NODE_ENV
              Value: !Ref EnvironmentId
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: LOG_LEVEL
              Value: DEBUG
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

# ======================
# ECS SERVICE
# ======================

  ECSService:
    Type: AWS::ECS::Service
    DependsOn: HTTPSListener
    Properties:
      Cluster: !Sub "${EnvironmentId}-${Module}-cluster"
      ServiceName: !Sub "${EnvironmentId}-${Module}-service"
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref PublicSubnetIDs
          SecurityGroups:
            - !Ref ECSSecurityGroup
      LoadBalancers:
        - ContainerName: api
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup

Outputs:

  LoadBalancerDNS:
    Description: ALB DNS
    Value: !GetAtt ApplicationLoadBalancer.DNSName