


### SRI Endpoints Test
### Generate SRI Invoice
POST {{host}}/api/sri/test/invoice
Content-Type: application/json
X-API-Key: 1716004948001_live_Aw8P3xGovxKEuC8F-9EMflP9_KWX1w3G

{
    "factura": {
        "signature":"Gocu71421Fir",
        "razonSocial": "Distribuidora de Suministros Nacional S.A.",
        "nombreComercial": "Empresa Importadora y Exportadora de Piezas",
        "dirMatriz": "Enrique Guerrero Portilla OE1-34 AV. Galo Plaza Lasso",
        "estab": "002",
        "ptoEmi": "001",
        "secuencial": "000000001",
        "fechaEmision" : "",
        "dirEstablecimiento" : "Sebastian Moreno S/N Franciso Garcia",
        "contribuyenteEspecial" : "5368",
        "obligadoContabilidad" : "SI",
        "tipoIdentificacionComprador" : "05",
        "guiaRemision" : "001-002-000000123",
        "razonSocialComprador" : "Juan Carlos Perez Lopez",
        "identificacionComprador" : "1719923456",
        "direccionComprador" : "Av. Amazonas N34-567 y Av. Colon",
        "totalSinImpuestos" : 10.00,
        "totalDescuento" : 0.00,
        "totalConImpuestos": [
               
                {
                    "codigo": 2,
                    "codigoPorcentaje": 2,
                    "baseImponible": 0.00,
                    "valor": 1.50
                }
            
        ],
        "propina" : 0.00,
        "importeTotal" : 11.50,
        "moneda" : "DOLAR",
        "pagos" : [
            {
                "formaPago" : "01",
                "total" : 11.50,
                "plazo" : 30,
                "unidadTiempo" : "DIA"
            }
        ],
        "valorRetIva" : 0.00,
        "valorRetRenta" : 0.00
    },
    "detalles": [
        {
            "codigoPrincipal": "125BJC-01",
            "codigoAuxiliar": "1234D56789-A",
            "descripcion": "Bujia de encendido para motor 1.8L",
            "precioUnitario": 10.00,
            "cantidad": 1,
            "descuento": 0.00,
            "precioTotalSinImpuesto": 9.00,
            "detallesAdicionales": [
                {
                    "nombre": "Marca",
                    "valor": "Bosch"
                },
                {
                    "nombre": "Modelo",
                    "valor": "X123YZ45"
                }
            ],
            "impuestos": [
               
                {
                    "codigo": 2,
                    "codigoPorcentaje": 2,
                    "tarifa": 15.00,
                    "baseImponible": 0.00,
                    "valor": 1.50
                }
            ]
        }
    ],
    "infoAdicional": [
        {
            "nombre": "Contacto",
            "value": "Juan Perez"
        },
        {
            "nombre": "Email",
            "value": "juan.perez@example.com"
        }
    ]    
}