export enum VOUCHER_STATUS {
    INITIAL = 'INITIAL',
    GENERATED = 'GENERATED',
    SIGNED = 'SIGNED',
    RECEIVED = 'RECEIVED',
    PROCESSING = 'PROCESSING',
    REJECTED = 'REJECTED',
    AUTHORIZED = 'AUTHORIZED',
    NOT_AUTHORIZED = 'NOT_AUTHORIZED'
}