export enum VOUCHER_STATUS {
    GENERATED = 'GENERATED',
    SIGNED = 'SIGNED',
    VALIDATED = 'VALIDATED',
    REJECTED = 'REJECTED',
    AUTHORIZED = 'AUTHORIZED',
    NOT_AUTHORIZED = 'NOT_AUTHORIZED',
    ERROR = 'ERROR'
}