export enum PAYMENT_METHOD {
  SIN_UTILIZACION_DEL_SISTEMA_FINANCIERO = "01",
  COMPENSACION_DE_DEUDAS = "15",
  TARJETA_DE_DEBITO = "16",
  DINERO_ELECTRONICO = "17",
  TARJETA_PREPAGO = "18",
  TARJETA_DE_CREDITO = "19",
  OTROS_CON_SISTEMA_FINANCIERO = "20",
  ENDOSO_DE_TITULOS = "21",
}
